IMIS/IMIS.vbproj
IMIS/Web.Debug.config.dist
IMIS/Web.Release.config.dist
IMIS/packages.config
IMIS/web.base.config
IMIS_BI/IMIS_BI.vbproj
IMIS_BI/packages.config
IMIS_BL/IMISExtractsBL.vb
IMIS_BL/IMIS_BL.vbproj
IMIS_BL/packages.config
IMIS_DAL/IMIS_DAL.vbproj
IMIS_DAL/packages.config
IMIS_EN/IMIS_EN.vbproj

Related to: https://openimis.atlassian.net/browse/OS-9

OS-9: Offline data files encryption

---

IMIS/Claim.aspx

Fix display of forgotten required field
TASK:
https://openimis.atlassian.net/browse/OP-81

OP-81: Improved display of the required field

---

IMIS_DAL/PriceListMIDAL.vb
IMIS_DAL/PricelistMSDAL.vb

I have changed the invalid Null type for the Database (**Nothing** to **DbNull.Value**)
Task:
https://openimis.atlassian.net/browse/OP-132

OP-132: Replacing Nothing to DbNull.Value

---

IMIS/PriceListMI.aspx
IMIS/PriceListMI.aspx.designer.vb
IMIS/PriceListMS.aspx
IMIS/PriceListMS.aspx.designer.vb

**Done:**
-  improved code placement in files
+ `PriceListMI.aspx`
+ `PriceListMS.aspx`
-  I added the Data field validator as required (*)
`<asp:RequiredFieldValidator ID="txtDate_RequiredFieldValidator" runat="server" ErrorMessage="*" ControlToValidate="txtDate" ValidationGroup="check" Visible="True" ForeColor="Red" Display="Dynamic"></asp:RequiredFieldValidator>`
**TASK:**
https://openimis.atlassian.net/browse/OP-133

OP-133: Added RequiredFieldValidator for Date field

---

IMIS/Officer.aspx.vb

Change Sub operation to function during EO saving
Task:
https://openimis.atlassian.net/browse/OP-126

OP-126: If the enrolment officer is created with a weak login, no error is shown and the EO is not created

---

IMIS/IMISExtracts.aspx.vb

Task:
https://openimis.atlassian.net/browse/OTC-7

OTC-7: Comment on the fragment hiding the Upload Enrolments form

---

IMIS/AutoCompleteHandlers/AutoCompleteHandler.ashx.vb
IMIS/FindClaims.aspx

Task:
https://openimis.atlassian.net/browse/OP-148

OP-148: Change logic for Main Dg

---

IMIS/AutoCompleteHandlers/AutoCompleteHandler.ashx.vb
IMIS/ClaimOverview.aspx

Task:
https://openimis.atlassian.net/browse/OP-149

OP-149: Change logic for autocomplete in Main Dg

---

IMIS/FindClaimAdministrator.aspx

Task:
https://openimis.atlassian.net/browse/OP-146

OP-146: Change name HF to HF Code

---

IMIS_DAL/MedicalServicesDAL.vb

TASK:
https://openimis.atlassian.net/browse/OTC-110

OTC-110: Added ServiceUUID for generating view

---

IMIS/ClaimAdministrator.aspx
IMIS/ClaimAdministrator.aspx.vb
IMIS/Officer.aspx
IMIS/Officer.aspx.vb

TASK:
https://openimis.atlassian.net/browse/OTC-116

OTC-116: CA and Officer fixed login

---

IMIS/App_GlobalResources/Resource.fr.resx
IMIS/App_GlobalResources/Resource.resx
IMIS_BL/EscapeBL.vb
IMIS_BL/PolicyBL.vb
IMIS_DAL/IMISDefaultsDAL.vb
IMIS_DAL/UtilitiesDAL.vb

Added ActivationOption for Policies
TASK:
https://openimis.atlassian.net/browse/OTC-67

OTC-67: RFC-116 New state of policies

---

IMIS/IMIS.vbproj
IMIS/Premium.aspx.vb
IMIS_BL/PolicyBL.vb
IMIS_DAL/PolicyDAL.vb

Related ticket: https://openimis.atlassian.net/browse/OTC-67

OTC-67: Changed code of one of policy status

---

IMIS_DAL/HealthFacilityDAL.vb

TICKET: [OP-242](https://openimis.atlassian.net/browse/OP-242)

OP-242: HF Code dropdown list don't display facilities

---

IMIS/Default.aspx.vb

Ticket: [OP-252](https://openimis.atlassian.net/browse/OP-252)

OP-252: Enforce recreation of CultureInfo cookie on login

---

IMIS_DAL/LocationsDAL.vb

TICKET: [OP-259](https://openimis.atlassian.net/browse/OP-259)

OP-259: Fix display of districts in user creation view

---

IMIS/User.aspx.vb

TICKET: [OP-195](https://openimis.atlassian.net/browse/OP-195)

OP-195: Disable password field for associated user in user view

---

IMIS/IMISExtracts.aspx.vb
IMIS_BL/IMISExtractsBL.vb

TICKET: [OP-178](https://openimis.atlassian.net/browse/OP-178)

OP-178: Fix PhotoExtract functionality

---

IMIS_DAL/PolicyDAL.vb

TICKET: [OTC-44](https://openimis.atlassian.net/browse/OTC-44)

OTC-44: Fix policyValue update contition

---

IMIS/Reports/rptClaimOverviewHistoryAllDetails.rdlc
IMIS_DAL/ReportDAL.vb

TICKET: [OTC-45](https://openimis.atlassian.net/browse/OTC-45)

OTC-45: Fixed Claim History All Details report

---

IMIS_BL/IMISExtractsBL.vb

TICKET: [OTC-11](https://openimis.atlassian.net/browse/OTC-11)

OTC-11: Corrupted XML enrolments won't break upload

---

IMIS/Reports.aspx.vb
IMIS_DAL/ReportDAL.vb

TICKET: [OTC-162](https://openimis.atlassian.net/browse/OTC-162)

OTC-162: Fix Overview of Commissions No Data issue

---

IMIS_DAL/ProductsDAL.vb

Treating location as a it's own parent caused duplication of records.

Fix parentLocation fetching in Policy view

---

IMIS/ProcessBatches.aspx.vb

TICKET: [OTC-189](https://openimis.atlassian.net/browse/OTC-189)

OTC-189: Fix batch run year dropdown

---

IMIS/.gitignore
IMIS/My Project/PublishProfiles/.gitignore
IMIS_DAL/PolicyDAL.vb

https://openimis.atlassian.net/browse/OP-129

OP-129: Fix inactive insurees checkbox in policies

---

IMIS/IMIS.Master.vb

Changes:
- Updated control setting names in IMIS.Master, now visibility of FSP fields in Enquiry can be controlled

OP-231: Enquiry function displayes not used fields FSP

---

IMIS_BL/IMISExtractsBL.vb
IMIS_DAL/IMISExtractsDAL.vb

changes:
-Added claim admins info to phone extract
https://openimis.atlassian.net/browse/OTC-108

OTC-108: It is possible to run IMIS Claims only with on-line initialization

---

IMIS_BL/ClaimsBL.vb
IMIS_DAL/LocationsDAL.vb

TICKET:  https://openimis.atlassian.net/browse/OTC-239
That ticket is related to that PR https://github.com/openimis/web_app_vb/pull/89 and comment:
This two function were fixed by me to handle None in case of no results.

OTC-239: NULL when no claims with id or uuid in ClaimsBl.vb

---

IMIS/Reports/rptControlNumberAssignment.rdlc
IMIS_DAL/ReportDAL.vb

TICKET: [OTC-31](https://openimis.atlassian.net/browse/OTC-31)

OTC-31: Fix Control Number Assignment report 

---

IMIS/PaymentOverview.aspx
IMIS/PaymentOverview.aspx.designer.vb
IMIS/PaymentOverview.aspx.vb
IMIS_BL/PaymentBL.vb

TICKET: https://openimis.atlassian.net/browse/OTC-278
web app part
error will be displayed like in below screenshot

OTC-278: show error in RejectedReason in webapp payment page

---

IMIS_DAL/ReportingDAL.vb

Changes:
- Changed title of OoC report to start with reporting date instead of scope
[https://openimis.atlassian.net/browse/OTC-70](https://openimis.atlassian.net/browse/OTC-70)

OTC-70: Report Overview of Commissions

---

IMIS/Officer.aspx

Changes:
- Deleted `toggleCheckWards` call from `toggleCheckVillages` to fix Infinite loop in the view
- Changed `toggleCheckVillages` to only affect visible villages
- Changed `toggleCheckWards` to first update visibility of villages and then to select all
[https://openimis.atlassian.net/browse/OTC-307](https://openimis.atlassian.net/browse/OTC-307)

OTC-307: Fixed infinite loop in Officer.aspx

---

IMIS/ClaimAdministrator.aspx
IMIS/Officer.aspx

Changes:
- Email requirement from `User.aspx` added to `Officer.aspx` and `ClaimAdministrator.aspx`
[https://openimis.atlassian.net/browse/OTC-46](https://openimis.atlassian.net/browse/OTC-46)

OTC-46: Email should be mandatory in EO/CA form

---

IMIS_BL/EscapeBL.vb
IMIS_BL/IMISExtractsBL.vb

Changes:
- Moved ImageToBlob from IMISExtractsBL to EscapeBL to allow for custom loading of photos (additional compression, resizing)

OTC-361: Fix offline enquiring in Claims app

---

IMIS/Family.aspx.vb

https://openimis.atlassian.net/browse/OTC-280

OTC-280: Add family-municipalities and villages not offered in the drop down menus

---

IMIS/App_GlobalResources/Resource.fr.resx
IMIS/App_GlobalResources/Resource.resx
IMIS/App_GlobalResources/Resource1.designer.vb

https://openimis.atlassian.net/browse/OTC-393

OTC-393: Batch Processing form crashing on load

---

IMIS/App_GlobalResources/Resource.fr.resx
IMIS/App_GlobalResources/Resource.resx
IMIS/App_GlobalResources/Resource1.designer.vb

https://openimis.atlassian.net/browse/OTC-398

OTC-398: Update the resource files

---

IMIS/Family.aspx.vb

https://openimis.atlassian.net/browse/OTC-400

OTC-400: MV: district ,municipality and village are automatically filled in although there are more options in the form Family

---

IMIS/Family.aspx.vb
IMIS/IMIS.vbproj
IMIS/web.base.config

https://openimis.atlassian.net/browse/OTC-402

OTC-402: MV: FSP  District automatically filled with the first option in the field  FSP District

---

IMIS/Family.aspx
IMIS/Family.aspx.designer.vb
IMIS/IMIS.vbproj

https://openimis.atlassian.net/browse/OTC-403

OTC-403: MV: unify the position of Vulnerability field

---

IMIS/Reports.aspx.vb
IMIS_BI/IMIS_BI.vbproj

https://openimis.atlassian.net/browse/OTC-70?focusedCommentId=13778

OTC-70: RFC  103  Report Overview of Commissions

---

IMIS/Javascripts/Exact.js
IMIS/StyleSheets/Imis.css

https://openimis.atlassian.net/browse/OTC-483

OTC-483: Remove this feature (Select2())

---

IMIS/FindPayment.aspx
IMIS/FindPayment.aspx.designer.vb
IMIS/FindPayment.aspx.vb
IMIS_BL/General.vb
IMIS_DAL/PaymentDAL.vb
IMIS_EN/tblPayment.vb

https://openimis.atlassian.net/browse/OTC-487

OTC-487: Add checkbox to filter reconciliated payments in find payments 

---

IMIS/App_GlobalResources/Resource.fr.resx
IMIS/App_GlobalResources/Resource.resx
IMIS/App_GlobalResources/Resource1.designer.vb
IMIS/Officer.aspx.designer.vb
IMIS/Officer.aspx.vb

Checks if the works to date is set then substitute officer becomes mandatory and vice-versa
https://openimis.atlassian.net/browse/OTC-491

OTC-491: Ensure a substitution of an enrolment officer in case the enrolment officer stops working. 

---

IMIS_BL/IMISExtractsBL.vb
IMIS_EN/Renewal.vb

Changes:
- Added `RenewalUUID` to `Renewal` model
- Included `RenewalUUID` field in renewal extract
[https://openimis.atlassian.net/browse/OP-187](https://openimis.atlassian.net/browse/OP-187)

OP-187: IMIS web and policies app: Renewal extracts dont work

---

IMIS/App_GlobalResources/Resource.resx
IMIS/Home.aspx
IMIS/Home.aspx.designer.vb
IMIS/Home.aspx.vb
IMIS/Registers.aspx.vb
IMIS_BL/HealthFacilityBL.vb
IMIS_BL/ICDCodesBL.vb
IMIS_BL/LocationsBL.vb

https://openimis.atlassian.net/browse/OS-79
Changes:
* To prevent XXE exploit XML resolver has been turned off for each of the uploads type (Diagnoses, Locations, Health Facilities)

OS-79: Fixed XXE issue with registers upload.

---

IMIS/App_GlobalResources/Resource.resx
IMIS/Home.aspx
IMIS/Home.aspx.designer.vb
IMIS/Home.aspx.vb

Changes:
* Added hidden field to show alert.
* Added alert for admin if default secret keys were not changed.
* Added labels in resources.
https://openimis.atlassian.net/browse/OS-82

OS-82 Default secret keys warning added for Admin on homepage.

---

IMIS/Home.aspx
IMIS/Home.aspx.designer.vb
IMIS/Home.aspx.vb
IMIS/Registers.aspx.vb
IMIS_BL/HealthFacilityBL.vb
IMIS_BL/ICDCodesBL.vb
IMIS_BL/LocationsBL.vb

Hotfix of security issues.
Changes:
- Alert showing if user hasn't changed default secret keys https://openimis.atlassian.net/browse/OS-82 
- LFI exploit patched https://openimis.atlassian.net/browse/OS-80
- XXE exploit patched https://openimis.atlassian.net/browse/OS-79

Hotfix security audit.

---

IMIS/Officer.aspx.vb

https://openimis.atlassian.net/browse/OTC-514
Changes:
- Fixed casting errors in two if checks that were throwing an exception

OTC-514: Fixed casting error in Officer form.

---

IMIS/Premium.aspx.vb

https://openimis.atlassian.net/browse/OTC-533

OTC-533: ThreadAbortException in the premium page

---

IMIS/Reports.aspx.vb

https://openimis.atlassian.net/browse/OTC-13

OTC-13: Optimise the report selection form

---

IMIS.sln
IMIS/IMIS.vbproj
IMIS/Reports.aspx.vb

https://openimis.atlassian.net/browse/OTC-70

OTC-103: RFC  103  Report Overview of Commissions

---

IMIS_DAL/PolicyDAL.vb

https://openimis.atlassian.net/browse/OTC-545

OTC-545: Policy Update: History dates are not maintained correctly

---

IMIS/Reports.aspx.vb

https://openimis.atlassian.net/browse/OTC-570
Changes:
- Input checks in reports rewritten
- Additional checks added when appropriate

OTC-570:  Input checks for reports rewritten and upgraded

---

IMIS_BL/EmailHandler.vb
IMIS_DAL/EmailSettingsDAL.vb

Reading Sender's display name from DB rather than hard coded string
https://openimis.atlassian.net/browse/OP-248

OP-248: Remove hardcodded _CompanyName in EmailHandler

---

IMIS/Officer.aspx
IMIS/Officer.aspx.designer.vb

https://openimis.atlassian.net/browse/OTC-491
Changes:
- Red outline added to substitution officer field.

OTC-491-2: Red outline added to required field.

---

IMIS/Global.asax.vb
IMIS/Web.Debug.config.dist

TICKET: [OTC-655](https://openimis.atlassian.net/browse/OTC-655)

OTC-655: Fixed culture not found error

---

IMIS/Reports.aspx.vb

TICKET: [OTC-672](https://openimis.atlassian.net/browse/OTC-672)

OTC-672: Fixed Contribution Distribution report

---

IMIS_BL/IMISExtractsBL.vb

Ticket: https://openimis.atlassian.net/browse/OP-937
Changes:
- SQL syntax error for phone extracts creation fixed.

OP-937: Phone extract SQL bug fixed.

---

IMIS_DAL/UsersDAL.vb
IMIS_EN/Web.config

https://openimis.atlassian.net/browse/OTC-733

OTC-733: Create user with English language throws an exception
