- IMIS_DAL/UsersDAL.vb
Change in getUsersDistricts function prevents displaying same district multiple times in home screen. 
Ticket: [OP-181](https://openimis.atlassian.net/browse/OP-181)
> OP-181: Removed duplicated districts names in home screen

- IMIS/OverviewFamily.aspx
- IMIS_DAL/PolicyDAL.vb
Quick retrieving of product from OverviewFamily was failing due to using product id instead of product uuid.
Ticket: [OP-221](https://openimis.atlassian.net/browse/OP-221)
> OP-221: Fixed retrieving product definition from OverviewFamily

- IMIS_DAL/PolicyRenewalDAL.vb
Execution of uspPolicyStatusUpdate procedure was added to PolicyRenewal update.
That allows changing expired policies status from web app, without using Windows Service.
TICKET: [OP-175](https://openimis.atlassian.net/jira/software/c/projects/OP/issues/OP-175)
> OP-175: PolicyRenewal updates expired policy status

- IMIS/OverviewFamily.aspx
Using L_PAYMENTTYPE  instead of L_TYPEOFPAYMENT resulted in using the wrong lokalise translation for BEPHA.
TICKET: [OP-189](https://openimis.atlassian.net/browse/OP-189)
> OP-189: Changed OverviewFamily payment type label

- IMIS_DAL/ProductsDAL.vb
During policy creation in the product dropdown list, single product could be displayed multiple times. 
This fix ensures that every product will be displayed only once.
> Remove duplicates from product dropdown list in Policy view

- IMIS/FindClaims.aspx.vb
Permission for claim review (instead of submit) is required to submit a claim, therefore some users can't submit claims even though they have proper permission.
> Fixed permission check for claims submssion

- IMIS/IMIS.vbproj
- IMIS/My Project/PublishProfiles/IMIS CHF Release.pubxml
- IMIS/My Project/PublishProfiles/IMIS MV Release.pubxml
- IMIS/User.aspx.vb
- IMIS_DAL/ClaimAdminDAL.vb
- IMIS_DAL/HealthFacilityDAL.vb
- IMIS_DAL/LocationsDAL.vb
- IMIS_DAL/OfficersDAL.vb
- IMIS_DAL/PayersDAL.vb
- IMIS_DAL/UsersDAL.vb
Changes:
- Made Admin account name unchangable
- Added checks for Admin acoount in several search queries
Unrelated changes:
- Added publish configuration for MV Release and CHF Release web apps.
> OTC-76: The get officers SQL must use admin role

- IMIS/Policy.aspx.vb
TICKET: https://openimis.atlassian.net/browse/OTC-183
In that PR I want to merge fix for the issue described in above ticket. Now is possible to change "enrolment date" - the product is not dismissing from field.
> OTC-183: fix dismissing insurance product

- IMIS/Claim.aspx.vb
- IMIS_BI/ClaimBI.vb
- IMIS_BL/ClaimsBL.vb
- IMIS_DAL/ClaimsDAL.vb
TICKET: https://openimis.atlassian.net/browse/OTC-160
In that PR I want to fix bug described in that ticket. Now after my fixes there is no error when user want to restore claim after saving new claim. The error was due to different URL structure after saving new claim (comparing to page when we enter to claim details)
> OTC-160: fixed bug with restore after saving new claim

- IMIS_DAL/LocationsDAL.vb
TICKET: https://openimis.atlassian.net/browse/OP-304
I think problem was related to the some inline SQLs in "LocationDAL.vb". Some "SELECTs" doesn't contain a condition to not fetch RegionName called "Funding".
This problem will be solved after my changes in such pages as:
- User
- Location
- Product
- Family
- Insuree
- MainPage (where we have list of regions available for current logged user)
> OP-304: Funding region should not be displayed

- IMIS/Claim.aspx.vb
Changes:
- Changed B_ADD_Click not to reference current session to generate cleared rows, instead resused the ServiceItemGridBinding call.
[https://openimis.atlassian.net/browse/OTC-248](
https://openimis.atlassian.net/browse/OTC-248)
> OTC-248: USERS CANT ADD SERVICE CODE UNDER CLAIM - HEALTH FACILITY CLAIMS

- IMIS/ChangeFamily.aspx.vb
- IMIS/Family.aspx.vb
- IMIS_BI/ChangeFamilyBI.vb
- IMIS_BI/FamilyBI.vb
- IMIS_BL/LocationsBL.vb
Changes:
- Made location related calls always respect the `showSelect` flag (deleted hardcoded `showSelect` values and additional condisions regarding number of rows)
- Changed values of `showSelect` flag in Family.aspx and ChangeFamily.apsx to `False`
[https://openimis.atlassian.net/browse/OTC-68](https://openimis.atlassian.net/browse/OTC-68)
> OTC-68: RFC 115 Supressing of automatic filling of locations

- IMIS/Reports.aspx
- IMIS/Reports.aspx.vb
- IMIS_BI/ReportsBI.vb
- IMIS_BL/ReportingBL.vb
- IMIS_DAL/ReportingDAL.vb
Changes:
- Added additional events to reload previous reports when year, month, region or district are changed
- Fixed `ddlYear`, using display name as value (which happened to be the same for all but one entry)
- Modified the query to allow retrieving previous reports based on any number of fields
- Fixed setting up mode of selected report
[https://openimis.atlassian.net/browse/OTC-70](https://openimis.atlassian.net/browse/OTC-70)
> OTC-70: RFC 103 Report Overview of Commissions

- IMIS_DAL/PaymentDAL.vb
TICKET: https://openimis.atlassian.net/browse/OTC-278
Fix issue raised by @dragos-dobre 
Payment Overview : Admin : System.IndexOutOfRangeException: There is no row at position 0.
at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
at System.Data.DataRowCollection.get_Item(Int32 index)
at IMIS.PaymentOverview.LoadDetails() in C:\Users\user\Documents\web_app_vb\IMIS\PaymentOverview.aspx.vb:line 316
at IMIS.PaymentOverview.loadGrid() in C:\Users\user\Documents\web_app_vb\IMIS\PaymentOverview.aspx.vb:line 99
at IMIS.PaymentOverview.Page_Load(Object sender, EventArgs e) in C:\Users\user\Documents\web_app_vb\IMIS\PaymentOverview.aspx.vb:line 81
It was because cancelled payment has set 'ValidityTo'. And that getPaymentDetails obtain only Payment with ValidityTo = NULL
> OTC-278: fix displaying payment with validity to not null

- IMIS/PaymentOverview.aspx
- IMIS/PaymentOverview.aspx.designer.vb
- IMIS/PaymentOverview.aspx.vb
part of TICKET: https://openimis.atlassian.net/browse/OTC-273
another change requested by @dragos-dobre  to show paymentId (billId) instead of payment uuid (internal id).
> OTC-273: display payment id in payment overview instead of uuid

- IMIS/App_GlobalResources/Resource.en_cm.resx
- IMIS/App_GlobalResources/Resource.en_tz.resx
- IMIS/App_GlobalResources/Resource.es_es.resx
- IMIS/App_GlobalResources/Resource.fr.resx
- IMIS/App_GlobalResources/Resource.fr_cd.resx
- IMIS/App_GlobalResources/Resource.fr_dj.resx
- IMIS/App_GlobalResources/Resource.fr_td.resx
- IMIS/App_GlobalResources/Resource.resx
- IMIS/App_GlobalResources/Resource.sw.resx
- IMIS/App_GlobalResources/Resource1.designer.vb
- IMIS/PaymentOverview.aspx.vb
part of TICKET: https://openimis.atlassian.net/browse/OTC-273
Change related to enhancements of showing 'Rejection reasons'. Including adding Swahili language for "Rejection reasons" label.
payment with rejection reasons:
no rejections reasons:
> OTC-273: works on display/hide rejection reasons

- IMIS_BL/BgServiceBL.vb
- IMIS_BL/EscapeBL.vb
Matching payment in background is implemented in RestAPI and therefore, it has been removed from WebApp.
https://openimis.atlassian.net/browse/OTC-330?focusedCommentId=13372
> OTC-330 : Removed MatchPayment method as it is not implemented in RestAPI

- IMIS_DAL/PricelistMSDAL.vb
Changes:
- Changed value for national price list from `Nothing` to `DBNull.Value` to fix the SQL exception on updating the price list
[https://openimis.atlassian.net/browse/OP-361](https://openimis.atlassian.net/browse/OP-361)
> OP-361: cannot add service to price list

- IMIS/IMIS.vbproj
- IMIS/Registers.aspx.vb
https://openimis.atlassian.net/browse/OTC-151
> OTC-151 : Missing statistics for uploading of health facilities into the register

- IMIS_DAL/HealthFacilityDAL.vb
Changes:
- Added DBNull value checks to LoadHF method for every nullable field
[https://openimis.atlassian.net/browse/OP-368](https://openimis.atlassian.net/browse/OP-368)
> OP-368: NULL value in HFAddress gives exception

- IMIS/Registers.aspx.vb
https://openimis.atlassian.net/browse/OS-80
Changes:
* Functions gets path for reports from settings file
* Functions sanitizes input by getting full path (no "example\..\..")
* Compares requested filepath with that in settings - if they are not the same no file is given to user.
> OS-80: Fixed LFI issue with report generating.

- IMIS/Reports.aspx.vb
- IMIS_BI/ReportsBI.vb
- IMIS_BL/ReportBL.vb
https://openimis.atlassian.net/browse/OTC-492
Changes:
- Claim overview now allows to check claims from the whole region, not only from the district as it was the case
- Changed variable name to be more appropriate (DistrictID -> LocationID)
- Claim overview now forces user to choose a region
This feature requires changes to the database:
https://github.com/openimis/database_ms_sqlserver/pull/124
> OTC-492: Fixed handling of region and district in claim overview.

- IMIS_BL/MedicalItemsBL.vb
- IMIS_BL/MedicalServicesBL.vb
Wild card added before and after the string in Items and Services search form
https://openimis.atlassian.net/browse/OP-171
> OP-171:  in service list, Service filters (Name and codes) don't find partial hits

- IMIS/OverviewFamily.aspx.vb
https://openimis.atlassian.net/browse/OTC-579
Changes:
- Overview insuree now can handle null value of ExpiryDate of policy attached.
> OTC-579: Insuree overview now can handle null ExpiryDate

- IMIS/Claim.aspx.vb
TICKET: https://openimis.atlassian.net/browse/OP-735
Changes: 
a) creating new claim in restored claim - no more updating existing claim (Initial claim is not changed)
a) for all Valid Claim : checked, processed and validated)
- remove insuree ID (CHF id)
- remove claim code
b) for rejected Claim
- add @ prefix to claim code
> OP-735: fixed 'restoring claim' functionality

- IMIS/Reports/rptClaimOverviewAllDetails.rdlc
TICKET: https://openimis.atlassian.net/browse/OTC-523
What is fixed:
- fixing displaying 'quantity' data in 'ClaimOverviewWithDetail' report.
Presentation of change based on demo data on localhost:
> OTC-523: correction of displaying report 'ClaimOverview with detail'

- IMIS/Reports.aspx
- IMIS/Reports.aspx.designer.vb
- IMIS/Reports.aspx.vb
Ticket: https://openimis.atlassian.net/browse/OTC-673
Changes:
* Overview of commission report does not require "Previous report" as input anymore
* Input option has been removed
* SQL has not been changed, instead NULL is passed as argument.
> OTC-673: Overview of Commission does not require Previous report input anymore.
